#' 1D-to-2D Function Stream Plot for ggplot2
#'
#' These functions provide convenient ggplot2 layers for drawing streams
#' generated by mapping a one-dimensional input (typically time) to
#' two-dimensional coordinates. A user-defined function (`fun`) specifies the
#' mapping by taking a numeric scalar (e.g. time) and returning a numeric vector
#' of length 2 (representing \eqn{(x, y)}). The underlying [Stat1d2d] evaluates
#' `fun` over a time sequence (from `t0` to `T` in increments of `dt`), and
#' [GeomStream] renders the resulting path.
#'
#' In many cases these layers are useful for visualizing dynamic systems or
#' flows where a one-dimensional parameter (often time) drives movement in
#' two-dimensional space.
#'
#' @inheritParams ggplot2::geom_path
#' @inheritParams geom_stream
#'
#' @param mapping A set of aesthetic mappings created by [ggplot2::aes()].
#'   Additional aesthetics such as `color`, `size`, `linetype`, and `alpha` can
#'   be defined. The default mapping sets `color = after_stat(t)`.
#' @param data A data frame containing the input data. In many cases, no data
#'   needs to be supplied.
#' @param stat The statistical transformation to use on the data for this layer.
#'   Defaults to [Stat1d2d].
#' @param position Position adjustment, either as a string or the result of a
#'   call to a position adjustment function.
#' @param na.rm Logical. If `FALSE` (the default), missing values are removed
#'   with a warning.
#' @param show.legend Logical. Should this layer be included in the legends?
#' @param inherit.aes Logical. If `FALSE`, overrides the default aesthetics
#'   rather than combining with them.
#' @param fun A function that defines the mapping from a scalar input (typically
#'   time) to a two-dimensional coordinate. It should take a numeric scalar and
#'   return a numeric vector of length 2 representing \eqn{(x, y)}.
#'   **(Required)**
#' @param t0 Numeric. The starting value of the time sequence. Defaults to `0`.
#' @param T Numeric. The ending value of the time sequence. Defaults to `10`.
#' @param dt Numeric. The time increment for evaluating `fun`. Defaults to
#'   `0.01`.
#' @param tail_point Logical. If `TRUE`, a point is drawn at the tail (starting
#'   position) of the stream.
#' @param arrow A [grid::arrow()] specification to add arrowheads to the stream.
#'   The default is a closed arrow with a 30° angle and a length of `0.02` npc.
#' @param ... Other arguments passed on to [ggplot2::layer()].
#'
#' @return A ggplot2 layer that computes and plots a stream by evaluating a
#'   one-dimensional function over a time sequence.
#'
#' @examples
#' # Define a simple function that maps time to a 2D coordinate (e.g., circular motion)
#' f <- function(t) {
#'   c(sin(t), cos(t))
#' }
#'
#' ggplot() +
#'   geom_function_1d2d(fun = f)
#'
#' f <- function(t) {
#'   c(sin(t), t*cos(t))
#' }
#'
#' ggplot() +
#'   geom_function_1d2d(fun = f, T = 20, tail_point = TRUE)
#'
#' @name geom_function_1d2d
#' @aliases geom_function_1d2d stat_function_1d2d Stat1d2d
#' @export
NULL
geom_function_1d2d <- function(mapping = NULL, data = NULL,
                              stat = Stat1d2d,
                              position = "identity",
                              ...,
                              na.rm = FALSE,
                              show.legend = NA,
                              inherit.aes = FALSE,
                              fun,
                              t0 = 0,
                              T = 10,
                              dt = 0.01,
                              tail_point = FALSE,
                              arrow = grid::arrow(angle = 30, length = grid::unit(0.02, "npc"),
                                                  type = "closed")
) {

  if (is.null(data)) data <- ensure_nonempty_data(data)

  default_mapping <- aes(color = after_stat(t))

  if (!is.null(mapping)) {
    if (!"color" %in% names(mapping) && !"colour" %in% names(mapping))
      mapping <- modifyList(default_mapping, mapping)
  } else {
    mapping <- default_mapping
  }

  layer(
    stat = stat,
    geom = GeomStream,
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      fun = fun,
      t0 = t0,
      T = T,
      dt = dt,
      na.rm = na.rm,
      tail_point = tail_point,
      arrow = arrow,
      ...
    )
  )
}

#' @rdname geom_function_1d2d
#' @format NULL
#' @usage NULL
#' @export
stat_function_1d2d <- function(mapping = NULL, data = NULL,
                               geom = GeomStream,
                               position = "identity",
                               ...,
                               na.rm = FALSE,
                               show.legend = NA,
                               inherit.aes = FALSE,
                               fun,
                               t0 = 0,
                               T = 10,
                               dt = 0.01,
                               n = 11,
                               tail_point = FALSE,
                               arrow = grid::arrow(angle = 30, length = grid::unit(0.02, "npc"),
                                                   type = "closed")
) {

  if (is.null(data)) data <- ensure_nonempty_data(data)

  default_mapping <- aes(color = after_stat(t))

  if (!is.null(mapping)) {
    if (!"color" %in% names(mapping) && !"colour" %in% names(mapping))
      mapping <- modifyList(default_mapping, mapping)
  } else {
    mapping <- default_mapping
  }

  layer(
    stat = Stat1d2d,
    geom = geom,
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      fun = fun,
      t0 = t0,
      T = T,
      dt = dt,
      na.rm = na.rm,
      tail_point = tail_point,
      arrow = arrow,
      ...
    )
  )
}

#' @rdname geom_function_1d2d
#' @format NULL
#' @usage NULL
#' @export
Stat1d2d <- ggproto("Stat1d2d", Stat,
  default_aes = aes(color = after_stat(t)),

  compute_group = function(data, scales, fun, t0, T, dt, ...) {

    t <- seq(t0, T, dt)

    stream_values <- t(sapply(t, fun))
    stream <- cbind(t, stream_values)
    colnames(stream) <- c("t", "x", "y")
    df <- as.data.frame(stream)

    df
  }
)
