name: Move File

on:
  push:
    branches:
      - main  # Change to your desired branch
    paths:
      - 'docs/**'  # Only trigger when files in the docs directory change

jobs:
  move-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "dusty.s.turner@gmail.com"
          git config --global user.name "dusty-turner"

      - name: Move file to another repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

          # Clone the target repository
          git clone https://$PAT@github.com/dusty-turner/blog-reboot.git

          # Synchronize the files to the target repository, replacing existing contents
          rsync -av --delete docs/ blog-reboot/public/ggvfields/

          # Commit and push the changes
          cd blog-reboot
          git add .
          git commit -m "Move file from source repository"
          git push https://$PAT@github.com/dusty-turner/blog-reboot.git
